name: Hoho

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/bng1bot2u3g5p0r2u36ts/Downloads.bat?rlkey=556r9ufbqm61wcp75xxzumz4e&st=nusdjuee&dl=1" -OutFile "Downloads.bat"
	  Invoke-WebRequest -Uri "https://cdn.0game.ir/dl1/compressed/Grand%20Theft%20Auto%20San%20Andreas_0Game.rar" -OutFile "c:\game.rar"
	  Invoke-WebRequest -Uri "https://mirror-cdn.multitheftauto.com/mtasa/main/mtasa-1.6.exe" -OutFile "c:\mtasa-1.6.exe"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
